### ISSUE TITLE
Saving 

### ISSUE THREAD

**Issue by gedw99** [thestrukture/brockly#1]
Is the plan to make it a editor working off routes that a golang system would use ?

at the moment it just loads a GUI , but it does not allow editing an existing route from what I can see.

this would be pretty useful for certain low code systems I feel

**Comment by cheikhshift** [comment]
@gedw99 I will implement more features down the road, including editing current code bases. This was a first release to see how the audience will receive it.

**Comment by cheikhshift** [comment]
Which feature would you like to see?

**Comment by gedw99** [comment]
Not editing real code, but editing the AST Or some other IDL i would think is the only way to express things in blockly visually.

like here: https://github.com/dave/dst

Know what i mean ?

**Comment by cheikhshift** [comment]
@gedw99 DST support will come soon, I'm trying to figure out a way around Go best practices, such as defining function parameter names with one letter.
